"""Bass lines."""

from __future__ import annotations

from pyoscillate.clock import NoteDivision
from pyoscillate.theory.catalog import Catalog
from pyoscillate.theory.interval import Interval
from pyoscillate.theory.phrase.base import Phrase, PhraseMode, Step


class BassLines(Catalog):
    """Bass lines as semitones above the current chord root, with an accent (and, for the funk line, a hold length) per step."""

    # bass lines: 16th steps, each carrying its semitone offset and accent
    BASS_TECHNO = Phrase(
        division=NoteDivision.SIXTEENTH,
        cycle=16,
        label="Techno bass: steady 16ths with an octave and a fifth leaning in",
        mode=PhraseMode.SEMITONES,
        category="Driving",
        steps=(
            Step(0, Interval.UNISON),
            Step(1, Interval.UNISON, accent=0.6),
            Step(2, Interval.UNISON, accent=0.6),
            Step(3, Interval.UNISON, accent=0.6),
            Step(4, Interval.UNISON, accent=0.9),
            Step(5, Interval.UNISON, accent=0.6),
            Step(6, Interval.OCTAVE, accent=0.6),
            Step(7, Interval.UNISON, accent=0.6),
            Step(8, Interval.UNISON),
            Step(9, Interval.UNISON, accent=0.6),
            Step(10, Interval.PERFECT_FIFTH, accent=0.6),
            Step(11, Interval.UNISON, accent=0.6),
            Step(12, Interval.UNISON, accent=0.9),
            Step(13, Interval.UNISON, accent=0.6),
            Step(14, Interval.UNISON, accent=0.6),
            Step(15, Interval.UNISON, accent=0.7),
        ),
    )
    BASS_ROLLING = Phrase(
        division=NoteDivision.SIXTEENTH,
        cycle=16,
        label="Rolling bass: constant 16ths moving through fifth, octave and minor third",
        mode=PhraseMode.SEMITONES,
        category="Driving",
        steps=(
            Step(0, Interval.UNISON),
            Step(1, Interval.UNISON, accent=0.72),
            Step(2, Interval.PERFECT_FIFTH, accent=0.72),
            Step(3, Interval.UNISON, accent=0.72),
            Step(4, Interval.UNISON),
            Step(5, Interval.OCTAVE, accent=0.72),
            Step(6, Interval.PERFECT_FIFTH, accent=0.72),
            Step(7, Interval.UNISON, accent=0.72),
            Step(8, Interval.UNISON),
            Step(9, Interval.UNISON, accent=0.72),
            Step(10, Interval.MINOR_THIRD, accent=0.72),
            Step(11, Interval.PERFECT_FIFTH, accent=0.72),
            Step(12, Interval.UNISON),
            Step(13, Interval.MINOR_SEVENTH, accent=0.72),
            Step(14, Interval.PERFECT_FIFTH, accent=0.72),
            Step(15, Interval.UNISON, accent=0.72),
        ),
    )
    BASS_DUB = Phrase(
        division=NoteDivision.SIXTEENTH,
        cycle=16,
        label="Dub bass: sparser, fifth and minor seventh answering the root",
        mode=PhraseMode.SEMITONES,
        category="Driving",
        steps=(
            Step(0, Interval.UNISON),
            Step(1, Interval.UNISON, accent=0.72),
            Step(2, Interval.UNISON, accent=0.72),
            Step(3, Interval.PERFECT_FIFTH, accent=0.72),
            Step(4, Interval.UNISON),
            Step(5, Interval.UNISON, accent=0.72),
            Step(6, Interval.MINOR_SEVENTH, accent=0.72),
            Step(7, Interval.UNISON, accent=0.72),
            Step(8, Interval.UNISON),
            Step(9, Interval.PERFECT_FIFTH, accent=0.72),
            Step(10, Interval.UNISON, accent=0.72),
            Step(11, Interval.UNISON, accent=0.72),
            Step(12, Interval.MINOR_THIRD),
            Step(13, Interval.UNISON, accent=0.72),
            Step(14, Interval.PERFECT_FIFTH, accent=0.72),
            Step(15, Interval.UNISON, accent=0.72),
        ),
    )
    BASS_MUTED = Phrase(
        division=NoteDivision.SIXTEENTH,
        cycle=16,
        label="Muted bass: short stabs, fifth, minor third and minor seventh",
        mode=PhraseMode.SEMITONES,
        category="Muted",
        steps=(
            Step(0, Interval.UNISON),
            Step(1, Interval.UNISON, accent=0.72),
            Step(2, Interval.UNISON, accent=0.72),
            Step(3, Interval.UNISON, accent=0.72),
            Step(4, Interval.PERFECT_FIFTH),
            Step(5, Interval.UNISON, accent=0.72),
            Step(6, Interval.UNISON, accent=0.72),
            Step(7, Interval.UNISON, accent=0.72),
            Step(8, Interval.UNISON),
            Step(9, Interval.UNISON, accent=0.72),
            Step(10, Interval.MINOR_THIRD, accent=0.72),
            Step(11, Interval.UNISON, accent=0.72),
            Step(12, Interval.UNISON),
            Step(13, Interval.PERFECT_FIFTH, accent=0.72),
            Step(14, Interval.UNISON, accent=0.72),
            Step(15, Interval.MINOR_SEVENTH, accent=0.72),
        ),
    )
    BASS_MUTED_B = Phrase(
        division=NoteDivision.SIXTEENTH,
        cycle=16,
        label="Muted bass B: the same stabs landing on different steps",
        mode=PhraseMode.SEMITONES,
        category="Muted",
        steps=(
            Step(0, Interval.UNISON),
            Step(1, Interval.UNISON, accent=0.72),
            Step(2, Interval.PERFECT_FIFTH, accent=0.72),
            Step(3, Interval.UNISON, accent=0.72),
            Step(4, Interval.UNISON),
            Step(5, Interval.UNISON, accent=0.72),
            Step(6, Interval.MINOR_SEVENTH, accent=0.72),
            Step(7, Interval.UNISON, accent=0.72),
            Step(8, Interval.UNISON),
            Step(9, Interval.MINOR_THIRD, accent=0.72),
            Step(10, Interval.UNISON, accent=0.72),
            Step(11, Interval.UNISON, accent=0.72),
            Step(12, Interval.PERFECT_FIFTH),
            Step(13, Interval.UNISON, accent=0.72),
            Step(14, Interval.UNISON, accent=0.72),
            Step(15, Interval.MINOR_SEVENTH, accent=0.72),
        ),
    )
    BASS_FOREST = Phrase(
        division=NoteDivision.SIXTEENTH,
        cycle=16,
        label="Forest bass: rests on each beat, rolls the 16ths between kicks",
        mode=PhraseMode.SEMITONES,
        category="Sparse",
        steps=(
            Step(1, Interval.UNISON, accent=0.8),
            Step(2, Interval.UNISON, accent=0.95),
            Step(3, Interval.OCTAVE, accent=0.7),
            Step(5, Interval.UNISON, accent=0.8),
            Step(6, Interval.UNISON, accent=0.95),
            Step(7, Interval.OCTAVE, accent=0.7),
            Step(9, Interval.UNISON, accent=0.8),
            Step(10, Interval.UNISON, accent=0.95),
            Step(11, Interval.OCTAVE, accent=0.7),
            Step(13, Interval.UNISON, accent=0.8),
            Step(14, Interval.UNISON, accent=0.95),
            Step(15, Interval.MINOR_SECOND, accent=0.7),
        ),
    )
    BASS_CONVERSATION = Phrase(
        division=NoteDivision.SIXTEENTH,
        cycle=64,
        label="Conversation bass: sparse held notes over four bars",
        mode=PhraseMode.SEMITONES,
        category="Sparse",
        steps=(
            Step(0, Interval.UNISON, accent=0.75),
            Step(8, Interval.UNISON, accent=0.75),
            Step(16, Interval.UNISON, accent=0.75),
            Step(32, Interval.UNISON, accent=0.75),
            Step(40, Interval.PERFECT_FIFTH, accent=0.75),
            Step(48, Interval.UNISON, accent=0.75),
            Step(61, Interval.UNISON, accent=0.9),
        ),
    )
    BASS_CONVERSATION_B = Phrase(
        division=NoteDivision.SIXTEENTH,
        cycle=64,
        label="Conversation bass B: the third bar leans on the fifth",
        mode=PhraseMode.SEMITONES,
        category="Sparse",
        steps=(
            Step(0, Interval.UNISON, accent=0.75),
            Step(8, Interval.UNISON, accent=0.75),
            Step(16, Interval.UNISON, accent=0.75),
            Step(32, Interval.PERFECT_FIFTH, accent=0.75),
            Step(40, Interval.PERFECT_FIFTH, accent=0.75),
            Step(45, Interval.MINOR_SEVENTH, accent=0.9),
            Step(48, Interval.UNISON, accent=0.75),
            Step(56, Interval.UNISON, accent=0.75),
        ),
    )
    BASS_HOVER = Phrase(
        division=NoteDivision.SIXTEENTH,
        cycle=64,
        label="Hover bass: steady eighths, stepping up a bar at a time",
        mode=PhraseMode.SEMITONES,
        category="Sparse",
        steps=(
            Step(0, Interval.UNISON, accent=0.95),
            Step(2, Interval.UNISON, accent=0.8),
            Step(4, Interval.UNISON, accent=0.8),
            Step(6, Interval.UNISON, accent=0.8),
            Step(8, Interval.UNISON, accent=0.8),
            Step(10, Interval.UNISON, accent=0.8),
            Step(12, Interval.UNISON, accent=0.8),
            Step(14, Interval.UNISON, accent=0.8),
            Step(16, Interval.MINOR_SECOND, accent=0.95),
            Step(18, Interval.MINOR_SECOND, accent=0.8),
            Step(20, Interval.MINOR_SECOND, accent=0.8),
            Step(22, Interval.MINOR_SECOND, accent=0.8),
            Step(24, Interval.MINOR_SECOND, accent=0.8),
            Step(26, Interval.MINOR_SECOND, accent=0.8),
            Step(28, Interval.MINOR_SECOND, accent=0.8),
            Step(30, Interval.MINOR_SECOND, accent=0.8),
            Step(32, Interval.MINOR_THIRD, accent=0.95),
            Step(34, Interval.MINOR_THIRD, accent=0.8),
            Step(36, Interval.MINOR_THIRD, accent=0.8),
            Step(38, Interval.MINOR_THIRD, accent=0.8),
            Step(40, Interval.MINOR_THIRD, accent=0.8),
            Step(42, Interval.MINOR_THIRD, accent=0.8),
            Step(44, Interval.MINOR_THIRD, accent=0.8),
            Step(46, Interval.MINOR_THIRD, accent=0.8),
            Step(48, Interval.PERFECT_FOURTH, accent=0.95),
            Step(50, Interval.PERFECT_FOURTH, accent=0.8),
            Step(52, Interval.PERFECT_FOURTH, accent=0.8),
            Step(54, Interval.PERFECT_FOURTH, accent=0.8),
            Step(56, Interval.PERFECT_FOURTH, accent=0.8),
            Step(58, Interval.PERFECT_FOURTH, accent=0.8),
            Step(60, Interval.PERFECT_FOURTH, accent=0.8),
            Step(62, Interval.PERFECT_FOURTH, accent=0.8),
        ),
    )
    # one funk bar of 16ths, each entry (step, semitones, accent, length in
    # 16ths): root on the One, held; octave pops; minor 7th, 5th and minor
    # 3rd fills; dead-note ghosts between them. Every pitch is a tone of the
    # rack's minor-seventh chords, and the minor 7th on the last 16th glides
    # down into the next bar's root
    BASS_FUNK = Phrase(
        division=NoteDivision.SIXTEENTH,
        cycle=16,
        label="Funk bass: a syncopated bar of held notes, pops and ghosts",
        mode=PhraseMode.SEMITONES,
        category="Groove",
        steps=(
            Step(0, Interval.UNISON, length=1.8),
            Step(3, Interval.UNISON, accent=0.55, length=0.4),
            Step(4, Interval.OCTAVE, accent=0.9, length=0.6),
            Step(6, Interval.MINOR_SEVENTH, accent=0.75, length=0.9),
            Step(7, Interval.UNISON, accent=0.55, length=0.4),
            Step(9, Interval.PERFECT_FIFTH, accent=0.8, length=0.6),
            Step(10, Interval.UNISON, accent=0.55, length=0.4),
            Step(11, Interval.MINOR_THIRD, accent=0.8, length=0.9),
            Step(13, Interval.PERFECT_FIFTH, accent=0.7, length=0.5),
            Step(14, Interval.OCTAVE, accent=0.9, length=0.5),
            Step(15, Interval.MINOR_SEVENTH, accent=0.6, length=0.5),
        ),
    )
