"""Text-based DSP expression evaluator. Defined in pyo/lib/expression.py."""

__all__ = ['Expr']

from pyo import Expr
"""
Expr(input, expr='', outs=1, initout=0.0, mul=1, add=0)

Prefix audio expression evaluator.

Expr implements a tiny functional programming language that can be
used to write synthesis or signal processing algorithms.

For documentation about the language, see the module's documentation.

Params:
    input   -- Input signal(s) to process. If given a multi-stream PyoObject or a list of PyoObjects, each stream ca be retrieved with the syntax $x0[0], $x1[0], $x2[0], etc. $x[0] is the same as $x0[0].
    expr    -- Expression to evaluate as a string.
    outs    -- Number of output signals generated by the object. If 1 (the default), the last expression in the script is the output signal. Otherwise, output signals must be created with the `out` function. Available at initialization time only.
    initout -- Value used to initialize the output buffers. Use with caution! Defaults to 0.0.
"""
