"""Patch definitions for the free-running psyambient rack."""

from pyoscillate.patches.psyambient import (
    bass_chaos,
    bass_drone,
    bass_rumble,
    mid_arp,
    mid_canon,
    mid_generative,
    soundscape_filter,
    soundscape_fm,
    soundscape_wash,
)
from src.flet.base import PatchDef

PATCH_DEFS: list[PatchDef] = [
    PatchDef(
        "soundscape_fm",
        "Soundscape - chaotic FM pad",
        "Free-running FM pad driven by Rossler/Lorenz attractors.",
        soundscape_fm.build,
        soundscape_fm.PARAMETERS,
        0.6,
    ),
    PatchDef(
        "soundscape_filter",
        "Soundscape - filter-swept pad",
        "Static drone carved by a chaotically-swept resonant lowpass filter.",
        soundscape_filter.build,
        soundscape_filter.PARAMETERS,
        0.6,
    ),
    PatchDef(
        "soundscape_wash",
        "Soundscape - washy detuned pad",
        "SuperSaw smeared with chorus, reverb, and delay.",
        soundscape_wash.build,
        soundscape_wash.PARAMETERS,
        0.6,
    ),
    PatchDef(
        "mid_arp",
        "Mid - slow pentatonic arpeggio",
        "Fixed pentatonic melody, phase-locked to the shared clock.",
        mid_arp.build,
        mid_arp.PARAMETERS,
        0.6,
        rebuild_parameters=("step_bars",),
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "mid_generative",
        "Mid - generative melody",
        "Free-running generative melody, drawn at random every few seconds.",
        mid_generative.build,
        mid_generative.PARAMETERS,
        0.6,
        rebuild_parameters=("note_period", "note_duration"),
    ),
    PatchDef(
        "mid_canon",
        "Mid - two-voice canon",
        "Two generative melodic voices drifting in and out of alignment.",
        mid_canon.build,
        mid_canon.PARAMETERS,
        0.6,
        rebuild_parameters=(
            "voice_a_period",
            "voice_b_period",
            "voice_b_interval",
            "note_duration",
        ),
    ),
    PatchDef(
        "bass_drone",
        "Bass - slow-swelling sub drone",
        "Near-static low fundamental that breathes in level.",
        bass_drone.build,
        bass_drone.PARAMETERS,
        0.8,
    ),
    PatchDef(
        "bass_chaos",
        "Bass - chaotic sub drift",
        "Near-static low fundamental whose pitch wanders unpredictably.",
        bass_chaos.build,
        bass_chaos.PARAMETERS,
        0.8,
    ),
    PatchDef(
        "bass_rumble",
        "Bass - textural noise rumble",
        "Filtered BrownNoise blended with a faint sub sine.",
        bass_rumble.build,
        bass_rumble.PARAMETERS,
        0.8,
    ),
]
