"""Patch definitions for the free-running psyambient rack."""

from pyoscillate.patches.psyambient import (
    bass_chaos,
    bass_drone,
    bass_rumble,
    mid_arp,
    mid_canon,
    mid_generative,
    soundscape_filter,
    soundscape_fm,
    soundscape_wash,
)
from src.flet.base import PatchDef

PATCH_DEFS: list[PatchDef] = [
    PatchDef(
        "soundscape_fm",
        "Soundscape - chaotic FM pad",
        "Slow-morphing, unpredictable pad that never quite repeats itself.",
        soundscape_fm.build,
        soundscape_fm.PARAMETERS,
        0.6,
    ),
    PatchDef(
        "soundscape_filter",
        "Soundscape - filter-swept pad",
        "Sustained drone whose brightness sweeps and breathes unpredictably.",
        soundscape_filter.build,
        soundscape_filter.PARAMETERS,
        0.6,
    ),
    PatchDef(
        "soundscape_wash",
        "Soundscape - washy detuned pad",
        "Wide, hazy detuned wash that dissolves into echoing space.",
        soundscape_wash.build,
        soundscape_wash.PARAMETERS,
        0.6,
    ),
    PatchDef(
        "mid_arp",
        "Mid - slow pentatonic arpeggio",
        "Calm, consonant melodic line locked to the groove.",
        mid_arp.build,
        mid_arp.PARAMETERS,
        0.6,
        rebuild_parameters=("step_bars",),
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "mid_generative",
        "Mid - generative melody",
        "Ever-changing generative melody that never quite repeats.",
        mid_generative.build,
        mid_generative.PARAMETERS,
        0.6,
        rebuild_parameters=("note_period", "note_duration"),
    ),
    PatchDef(
        "mid_canon",
        "Mid - two-voice canon",
        "Two melodic voices in a slow-shifting call and response.",
        mid_canon.build,
        mid_canon.PARAMETERS,
        0.6,
        rebuild_parameters=(
            "voice_a_period",
            "voice_b_period",
            "voice_b_interval",
            "note_duration",
        ),
    ),
    PatchDef(
        "bass_drone",
        "Bass - slow-swelling sub drone",
        "Slow-breathing sub bed that swells and recedes.",
        bass_drone.build,
        bass_drone.PARAMETERS,
        0.8,
    ),
    PatchDef(
        "bass_chaos",
        "Bass - chaotic sub drift",
        "Living, unstable sub rumble whose pitch subtly wanders.",
        bass_chaos.build,
        bass_chaos.PARAMETERS,
        0.8,
    ),
    PatchDef(
        "bass_rumble",
        "Bass - textural noise rumble",
        "Unpitched, earthquake-like low-end texture.",
        bass_rumble.build,
        bass_rumble.PARAMETERS,
        0.8,
    ),
]
