"""Panning, mixing, and voice-routing objects. All defined in pyo/lib/pan.py."""

__all__ = ['Pan', 'SPan', 'Switch', 'Selector', 'VoiceManager', 'Mixer']

from pyo import Pan
"""
Pan(input, outs=2, pan=0.5, spread=0.5, mul=1, add=0)

Cosinus panner with control on the spread factor.

Params:
    input  -- Input signal to process.
    outs   -- Number of channels on the panning circle. Available at initialization time only. Defaults to 2.
    pan    -- Position of the sound on the panning circle, between 0 and 1. Defaults to 0.5.
    spread -- Amount of sound leaking to the surrounding channels, between 0 and 1. Defaults to 0.5.
"""

from pyo import SPan
"""
SPan(input, outs=2, pan=0.5, mul=1, add=0)

Simple equal power panner.

Params:
    input -- Input signal to process.
    outs  -- Number of channels on the panning circle. Available at initialization time only. Defaults to 2.
    pan   -- Position of the sound on the panning circle, between 0 and 1. Defaults to 0.5.
"""

from pyo import Switch
"""
Switch(input, outs=2, voice=0.0, mul=1, add=0)

Audio switcher.

Switch takes an audio input and interpolates between multiple outputs.

User can retrieve the different streams by calling the output number
between brackets. obj[0] retrieve the first stream, obj[outs-1] the
last one.

Params:
    input -- Input signal to process.
    outs  -- Number of outputs. Available at initialization time only. Defaults to 2.
    voice -- Voice position pointer, between 0 and (outs-1) / len(input). Defaults to 0.
"""

from pyo import Selector
"""
Selector(inputs, voice=0.0, mul=1, add=0)

Audio selector.

Selector takes multiple PyoObjects in input and interpolates between
them to generate a single output.

Params:
    inputs -- Audio objects to interpolate from.
    voice  -- Voice position pointer, between 0 and len(inputs)-1. Defaults to 0.
"""

from pyo import VoiceManager
"""
VoiceManager(input, triggers=None, mul=1, add=0)

Polyphony voice manager.

A trigger in input ask the object for a voice number and the object returns
the first free one. The voice number is then disable until a trig comes at
the same position in the list of triggers given at the argument `triggers`.

Usually, the trigger enabling the voice number will come from the process
started with the object output. So, it's common to leave the `triggers`
argument to None and set the list of triggers afterward with the `setTriggers`
method. The maximum number of voices generated by the object is the length
of the trigger list.

If there is no free voice, the object outputs -1.0 continuously.

Params:
    input    -- Trigger stream asking for new voice numbers.
    triggers -- List of mono PyoObject sending triggers. Can be a multi-streams PyoObject but not a mix of both. Ordering in the list corresponds to voice numbers. Defaults to None.
"""

from pyo import Mixer
"""
Mixer(outs=2, chnls=1, time=0.025, mul=1, add=0)

Audio mixer.

Mixer mixes multiple inputs to an arbitrary number of outputs
with independant amplitude values per mixing channel and a
user defined portamento applied on amplitude changes.

Params:
    outs  -- Number of outputs of the mixer. Available at initialization time only. Defaults to 2.
    chnls -- Number of channels per output. Available at initialization time only. Defaults to 1.
    time  -- Duration, in seconds, of a portamento applied on a new amplitude value for a mixing channel. Defaults to 0.025.
"""
