"""Trigger generation and trigger-reactive objects -- discrete event pulses and the objects that respond to them (envelopes, random draws, counters, rhythm generators). All defined in pyo/lib/triggers.py."""

__all__ = ['Trig', 'Metro', 'Seq', 'Cloud', 'Beat', 'TrigRandInt', 'TrigRand', 'TrigChoice', 'TrigFunc', 'TrigEnv', 'TrigLinseg', 'TrigExpseg', 'TrigXnoise', 'TrigXnoiseMidi', 'Counter', 'Select', 'Change', 'Thresh', 'Percent', 'Timer', 'Iter', 'Count', 'NextTrig', 'TrigVal', 'Euclide', 'TrigBurst']

from pyo import Trig
"""
Trig()

Sends one trigger.

A trigger is an audio signal with a value of 1 surrounded by 0s.

Trig sends a trigger each time it's play() method is called.

"""

from pyo import Metro
"""
Metro(time=1, poly=1)

Generates isochronous trigger signals.

A trigger is an audio signal with a value of 1 surrounded by 0s.

The play() method starts the metro and is not called at the object
creation time.

Params:
    time -- Time between each trigger in seconds. Defaults to 1.
    poly -- Metronome polyphony. Denotes how many independent streams are generated by the metronome, allowing overlapping processes. Available only at initialization. Defaults to 1.
"""

from pyo import Seq
"""
Seq(time=1, seq=[1], poly=1, onlyonce=False, speed=1)

Generates a rhythmic sequence of trigger signals.

A trigger is an audio signal with a value of 1 surrounded by 0s.

The play() method starts the sequence and is not called at the object
creation time.

Params:
    time     -- Base time between each trigger in seconds. Defaults to 1.
    seq      -- Sequence of beat durations in time's unit. Defaults to [1].
    poly     -- Seq polyphony. Denotes how many independent streams are generated by the metronome, allowing overlapping processes. Available only at initialization. Defaults to 1.
    onlyonce -- If True, the sequence will play only once and automatically stop. Defaults to False.
    speed    -- Continuous speed factor. This factor multiplies the speed of the internal timer continuously. It can be useful to create time deceleration or acceleration. Defaults to 1.
"""

from pyo import Cloud
"""
Cloud(density=10, poly=1)

Generates random triggers.

Generates random triggers with control over the generation density.

A trigger is an audio signal with a value of 1 surrounded by 0s.

The play() method starts the Cloud and is not called at the object
creation time.

Params:
    density -- Average number of triggers per second. Defaults to 10.
    poly    -- Cloud polyphony. Denotes how many independent streams are generated by the object, allowing overlapping processes. Available only at initialization. Defaults to 1.
"""

from pyo import Beat
"""
Beat(time=0.125, taps=16, w1=80, w2=50, w3=30, poly=1, onlyonce=False)

Generates algorithmic trigger patterns.

A trigger is an audio signal with a value of 1 surrounded by 0s.

Beat generates measures of length `taps` and uses weight parameters
(`w1`, `w2` and `w3`) to compute the chances of a beat to be present
in the generated measure.

User can store the current pattern in one of the 32 preset slots with
the store() method and recall it later with recall(x).

A preset is a list where the first value is the number of beats in the
measure, followed by 1s and 0s. For a 4/4 measure with only down beats:

[16, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]

The play() method starts the Beat and is not called at the object
creation time.

Params:
    time     -- Time, in seconds, between each beat of the pattern. Defaults to 0.125.
    taps     -- Number of beats in the generated pattern, max = 64. Defaults to 16.
    w1       -- Probability for down beats. Defaults to 80.
    w2       -- Probability for up beats. Defaults to 50.
    w3       -- Probability for the weakest beats. Defaults to 30.
    poly     -- Beat polyphony. Denotes how many independent streams are generated by the object, allowing overlapping processes. Available only at initialization. Defaults to 1.
    onlyonce -- If True, the sequence will play only once and automatically stop. Defaults to False.
"""

from pyo import TrigRandInt
"""
TrigRandInt(input, max=100.0, mul=1, add=0)

Pseudo-random integer generator.

TrigRandInt generates a pseudo-random number integer number between
0 and `max` values each time it receives a trigger in its `input`
parameter. The value is kept until the next trigger.

Params:
    input -- Audio signal sending triggers.
    max   -- Maximum value for the random generation. Defaults to 100.
"""

from pyo import TrigRand
"""
TrigRand(input, min=0.0, max=1.0, port=0.0, init=0.0, mul=1, add=0)

Pseudo-random number generator.

TrigRand generates a pseudo-random number between `min` and `max`
values each time it receives a trigger in its `input` parameter.
The value is kept until the next trigger.

Params:
    input -- Audio signal sending triggers.
    min   -- Minimum value for the random generation. Defaults to 0.
    max   -- Maximum value for the random generation. Defaults to 1.
    port  -- Portamento. Time to reach a new value. Defaults to 0.
    init  -- Initial value. Available at initialization time only. Defaults to 0.
"""

from pyo import TrigChoice
"""
TrigChoice(input, choice, port=0.0, init=0.0, mul=1, add=0)

Random generator from user's defined values.

TrigChoice chooses randomly a new value in list `choice` each
time it receives a trigger in its `input` parameter. The value
is kept until the next trigger.

Params:
    input  -- Audio signal sending triggers.
    choice -- Possible values for the random generation.
    port   -- Portamento. Time to reach a new value. Defaults to 0.
    init   -- Initial value. Available at initialization time only. Defaults to 0.
"""

from pyo import TrigFunc
"""
TrigFunc(input, function, arg=None)

Python function callback.

TrigFunc calls the function given at parameter `function` each
time it receives a trigger in its `input` parameter.

Params:
    input    -- Audio signal sending triggers.
    function -- Function to be called.
    arg      -- Argument sent to the function's call. If None, the function will be called without argument. Defaults to None.
"""

from pyo import TrigEnv
"""
TrigEnv(input, table, dur=1, interp=2, mul=1, add=0)

Envelope reader generator.

TrigEnv starts reading an envelope in `dur` seconds each time it
receives a trigger in its `input` parameter.

Params:
    input  -- Audio signal sending triggers.
    table  -- Table containing the envelope.
    dur    -- Duration in seconds of the envelope. Defaults to 1.
    interp -- Choice of the interpolation method. Defaults to 2. 1. no interpolation 2. linear 3. cosinus 4. cubic
"""

from pyo import TrigLinseg
"""
TrigLinseg(input, list, mul=1, add=0)

Line segments trigger.

TrigLinseg starts reading a break-points line segments each time it
receives a trigger in its `input` parameter.

Params:
    input -- Audio signal sending triggers.
    list  -- Points used to construct the line segments. Each tuple is a new point in the form (time, value). Times are given in seconds and must be in increasing order.
"""

from pyo import TrigExpseg
"""
TrigExpseg(input, list, exp=10, inverse=True, mul=1, add=0)

Exponential segments trigger.

TrigExpseg starts reading break-points exponential segments each time
it receives a trigger in its `input` parameter.

Params:
    input   -- Audio signal sending triggers.
    list    -- Points used to construct the line segments. Each tuple is a new point in the form (time, value). Times are given in seconds and must be in increasing order.
    exp     -- Exponent factor. Used to control the slope of the curves. Defaults to 10.
    inverse -- If True, downward slope will be inversed. Useful to create biexponential curves. Defaults to True.
"""

from pyo import TrigXnoise
"""
TrigXnoise(input, dist=0, x1=0.5, x2=0.5, mul=1, add=0)

Triggered X-class pseudo-random generator.

Xnoise implements a few of the most common noise distributions.
A new value is generated each time the object receive a trigger
in input. Each distribution generates values in the range 0 and 1.

Params:
    input -- Audio signal sending triggers.
    dist  -- Distribution type. Defaults to 0.
    x1    -- First parameter. Defaults to 0.5.
    x2    -- Second parameter. Defaults to 0.5.
"""

from pyo import TrigXnoiseMidi
"""
TrigXnoiseMidi(input, dist=0, x1=0.5, x2=0.5, scale=0, mrange=(0, 127), mul=1, add=0)

Triggered X-class midi notes pseudo-random generator.

Xnoise implements a few of the most common noise distributions.
A new value is generated each time the object receive a trigger
in input. Each distribution generates integer values in the range
defined with `mrange` parameter and output can be scaled on midi
notes, hertz or transposition factor.

Params:
    input  -- Audio signal sending triggers.
    dist   -- Distribution type. Defaults to 0.
    x1     -- First parameter. Defaults to 0.5.
    x2     -- Second parameter. Defaults to 0.5.
    scale  -- Output format. 0 = MIDI, 1 = Hertz, 2 = transposition factor. Defaults to 0. In the transposition mode, the central key (the key where there is no transposition) is (`minrange` + `maxrange`) / 2.
    mrange -- Minimum and maximum possible values, in Midi notes. Available only at initialization time. Defaults to (0, 127).
"""

from pyo import Counter
"""
Counter(input, min=0, max=100, dir=0, mul=1, add=0)

Integer count generator.

Counter keeps track of all triggers received, outputs the current
count constrained within `min` and `max` range, and can be set to
count up, down, or up-and-down.

Params:
    input -- Audio signal sending triggers.
    min   -- Minimum value of the count, included in the count. Defaults to 0.
    max   -- Maximum value of the count. excluded of the count. The counter will count up to max - 1. Defaults to 100.
    dir   -- Direction of the count. Defaults to 0. Three possible values: 0. up 1. down 2. up-and-down
"""

from pyo import Select
"""
Select(input, value=0, mul=1, add=0)

Sends trigger on matching integer values.

Select takes in input an audio signal containing integer numbers
and sends a trigger when the input matches `value` parameter. This
object is especially designed to be used with Counter object.

Params:
    input -- Audio signal. Must contains integer numbers.
    value -- Value to be matched to send a trigger. Defaults to 0.
"""

from pyo import Change
"""
Change(input, mul=1, add=0)

Sends trigger that informs when input value has changed.

Params:
    input -- Audio signal. Must contains integer numbers.
"""

from pyo import Thresh
"""
Thresh(input, threshold=0.0, dir=0, mul=1, add=0)

Informs when a signal crosses a threshold.

Thresh sends a trigger when a signal crosses a threshold. The `dir`
parameter can be used to set the crossing mode, down-up, up-down, or
both.

Params:
    input     -- Audio signal sending triggers.
    threshold -- Threshold value. Defaults to 0.
    dir       -- There are three modes of using Thresh: 0. down-up (default) sends a trigger when current value is higher than the threshold, while old value was equal to or lower than the threshold. 1. up-down sends a trigger when current value is lower than the threshold, while old value was equal to or higher than the threshold. 2. both direction sends a trigger in both the two previous cases.
"""

from pyo import Percent
"""
Percent(input, percent=50.0, mul=1, add=0)

Lets pass a certain percentage of the input triggers.

Percent looks at the triggers received in `input` and
lets them pass `percent` of the time.

Params:
    input   -- Audio signal sending triggers.
    percent -- How much percentage of triggers to let pass, between 0 and 100. Defaults to 50.
"""

from pyo import Timer
"""
Timer(input, input2, mul=1, add=0)

Reports elapsed time between two trigs.

A trigger in `input2` signal starts an internal timer. The next trigger
in `input` signal stops it and reports the elapsed time between the two
triggers. Useful for filtering triggers that are too close to each other.

Params:
    input  -- Trigger signal. Stops the timer and reports elapsed time.
    input2 -- Trigger signal. Starts the timer if not already started.
"""

from pyo import Iter
"""
Iter(input, choice, init=0.0, mul=1, add=0)

Triggers iterate over a list of values.

Iter loops over a list of user-defined values. When a trigger is received
in `input`, Iter moves up to the next value in the list, with wrap-around.

Params:
    input  -- Audio signal sending triggers.
    choice -- Sequence of values over which to iterate. If a PyoObject with more than one audio streams is given, the streams will be flattened and inserted in the main list. See setChoice method for more details.
    init   -- Initial value. Available at initialization time only. Defaults to 0.
"""

from pyo import Count
"""
Count(input, min=0, max=0, mul=1, add=0)

Counts integers at audio rate.

Count generates a signal increasing by 1 each sample when it receives a
trigger. It can be used to do sample playback using TableIndex.

Params:
    input -- Trigger signal. Start or Restart the count.
    min   -- Minimum value of the count, included in the count. Defaults to 0.
    max   -- Maximum value of the count. excluded of the count. Defaults to 0. A value of 0 eliminates the maximum, and the count continues increasing without resetting.
"""

from pyo import NextTrig
"""
NextTrig(input, input2, mul=1, add=0)

A trigger in the second stream opens a gate only for the next one in the first stream.

When the gate is opened by a trigger in `input2` signal, the next trigger
in `input` signal is allowed to pass and automatically closes the gate.

Params:
    input  -- Trigger signal. Trigger stream waiting for the gate to be opened.
    input2 -- Trigger signal. Trigger stream opening the gate.
"""

from pyo import TrigVal
"""
TrigVal(input, value=0.0, init=0.0, mul=1, add=0)

Outputs a previously defined value on a trigger signal.

Value defined at `value` argument is sent when a trigger signal
is detected in input.

Params:
    input -- Audio signal sending triggers.
    value -- Next value. Defaults to 0.
    init  -- Initial value. Defaults to 0.
"""

from pyo import Euclide
"""
Euclide(time=0.125, taps=16, onsets=10, poly=1)

Euclidean rhythm generator.

This object generates euclidean trigger patterns, resulting in onsets
in the rhythm to be as equidistant as possible.

A trigger is an audio signal with a value of 1 surrounded by 0s.

The play() method starts the Euclide and is not called at the object
creation time.

Params:
    time   -- Time, in seconds, between each beat of the pattern. Defaults to 0.125.
    taps   -- Number of beats in the generated pattern (measure length), max = 64. Defaults to 16.
    onsets -- Number of onsets (a positive tap) in the generated pattern. Defaults to 10.
    poly   -- Beat polyphony. Denotes how many independent streams are generated by the object, allowing overlapping processes. Available only at initialization. Defaults to 1.
"""

from pyo import TrigBurst
"""
TrigBurst(input, time=0.25, count=10, expand=1.0, ampfade=1.0, poly=1)

Generates a time/amplitude expandable trigger pattern.

A trigger is an audio signal with a value of 1 surrounded by 0s.

When TrigBurst receives a trigger in its `input` argument, it starts
to output `count` triggers with a variable delay between each trigger
of the pattern. If `expand` is less than 1.0, the delay becomes shorter,
if it is greater than 1.0, the delay becomes longer.

Params:
    input   -- Input signal sending triggers.
    time    -- Base time, in seconds, between each trig of the serie. Defaults to 0.25.
    count   -- Number of trigs generated (length of the serie). Defaults to 10.
    expand  -- Timing power serie factor. Each delay before the next trig is the current delay (starting with `time`) times `expand` factor. Defaults to 1.0.
    ampfade -- Amplitude power serie factor. Each amplitude in the serie is the current amplitude (starting at 1) times `ampfade` factor. Defaults to 1.0.
    poly    -- Voice polyphony. Denotes how many independent streams are generated by the object, allowing overlapping processes. Available only at initialization. Defaults to 1.
"""
