"""Patch definitions for the clock-locked deep-house rack."""

from pyoscillate.patches.deep_house import bass, chord, hat, kick, percussion
from src.flet.base import PatchDef

PATCH_DEFS: list[PatchDef] = [
    PatchDef(
        "kick_round",
        "Kick - Round",
        "Four-on-the-floor foundation.",
        kick.make_builder("round"),
        kick.PARAMETERS,
        kick.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "kick_punch",
        "Kick - Punch",
        "Four-on-the-floor foundation.",
        kick.make_builder("punch"),
        kick.PARAMETERS,
        kick.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "kick_soft",
        "Kick - Soft",
        "Four-on-the-floor foundation.",
        kick.make_builder("soft"),
        kick.PARAMETERS,
        kick.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "bass_rolling",
        "Bass - Rolling",
        "16th-note low-end movement.",
        bass.make_builder("rolling"),
        bass.PARAMETERS,
        bass.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "bass_dub",
        "Bass - Dub",
        "16th-note low-end movement.",
        bass.make_builder("dub"),
        bass.PARAMETERS,
        bass.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "bass_muted",
        "Bass - Muted",
        "16th-note low-end movement.",
        bass.make_builder("muted"),
        bass.PARAMETERS,
        bass.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "chord_velvet",
        "Chord Stab - Velvet",
        "Offbeat minor-seventh harmony.",
        chord.make_builder("velvet"),
        chord.PARAMETERS,
        chord.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "chord_organ",
        "Chord Stab - Organ",
        "Offbeat minor-seventh harmony.",
        chord.make_builder("organ"),
        chord.PARAMETERS,
        chord.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "chord_shimmer",
        "Chord Stab - Shimmer",
        "Offbeat minor-seventh harmony.",
        chord.make_builder("shimmer"),
        chord.PARAMETERS,
        chord.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "hat_crisp",
        "Hat - Crisp",
        "Offbeat and shuffled top texture.",
        hat.make_builder("crisp"),
        hat.PARAMETERS,
        hat.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "hat_open",
        "Hat - Open",
        "Offbeat and shuffled top texture.",
        hat.make_builder("open"),
        hat.PARAMETERS,
        hat.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "hat_shuffle",
        "Hat - Shuffle",
        "Offbeat and shuffled top texture.",
        hat.make_builder("shuffle"),
        hat.PARAMETERS,
        hat.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "percussion_clap",
        "Percussion - Clap",
        "Clap, rim, or conga rhythmic color.",
        percussion.make_builder("clap"),
        percussion.PARAMETERS,
        percussion.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "percussion_rim",
        "Percussion - Rim",
        "Clap, rim, or conga rhythmic color.",
        percussion.make_builder("rim"),
        percussion.PARAMETERS,
        percussion.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
    PatchDef(
        "percussion_conga",
        "Percussion - Conga",
        "Clap, rim, or conga rhythmic color.",
        percussion.make_builder("conga"),
        percussion.PARAMETERS,
        percussion.VOLUME_DEFAULT,
        needs_tempo=True,
        needs_clock=True,
    ),
]
